#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MarketingAutomationTool")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCOM_MESSAGE(COM_MESSAGE instance);
    partial void UpdateCOM_MESSAGE(COM_MESSAGE instance);
    partial void DeleteCOM_MESSAGE(COM_MESSAGE instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DAL.Properties.Settings.Default.MarketingAutomationToolConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<COM_MESSAGE> COM_MESSAGEs
		{
			get
			{
				return this.GetTable<COM_MESSAGE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COM_MESSAGE")]
	public partial class COM_MESSAGE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MESSAGE_ID;
		
		private string _NAME;
		
		private string _DESCRIPTION;
		
		private string _SUBJECT;
		
		private string _FROM_ADDRESS;
		
		private string _FROM_NAME;
		
		private string _CC;
		
		private string _BCC;
		
		private int _CHANNEL_ID;
		
		private int _FORMAT_ID;
		
		private string _BODY;
		
		private System.Nullable<int> _TEMPLATE_ID;
		
		private byte _STATUS_ID;
		
		private System.Nullable<System.DateTime> _SUBMITTED;
		
		private System.Nullable<long> _HTML_TEMPLATE_ID;
		
		private System.Nullable<long> _RECIPIENT_FILTER_ID;
		
		private System.Guid _UserId;
		
		private System.DateTime _CREATED;
		
		private System.Nullable<System.Guid> _UPDATE_USER_ID;
		
		private System.Nullable<System.Guid> _DELETE_USER_ID;
		
		private System.DateTime _DATE_CREATED;
		
		private System.Nullable<System.DateTime> _DATE_UPDATED;
		
		private System.Nullable<System.DateTime> _DATE_DELETED;
		
		private System.Data.Linq.Binary _VERSION;
		
		private string _ENTITY;
		
		private string _ENTITY_ID;
		
		private System.Nullable<int> _MSGTYPE;
		
		private System.Nullable<bool> _isLink;
		
		private string _FB_URL;
		
		private System.Nullable<bool> _REPLACE_EMAIL;
		
		private string _FB_PhotoUrl;
		
		private string _FB_SourceUrl;
		
		private System.Nullable<bool> _isSenderID;
		
		private string _TO_ADDRESS;
		
		private string _TO_NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMESSAGE_IDChanging(int value);
    partial void OnMESSAGE_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    partial void OnSUBJECTChanging(string value);
    partial void OnSUBJECTChanged();
    partial void OnFROM_ADDRESSChanging(string value);
    partial void OnFROM_ADDRESSChanged();
    partial void OnFROM_NAMEChanging(string value);
    partial void OnFROM_NAMEChanged();
    partial void OnCCChanging(string value);
    partial void OnCCChanged();
    partial void OnBCCChanging(string value);
    partial void OnBCCChanged();
    partial void OnCHANNEL_IDChanging(int value);
    partial void OnCHANNEL_IDChanged();
    partial void OnFORMAT_IDChanging(int value);
    partial void OnFORMAT_IDChanged();
    partial void OnBODYChanging(string value);
    partial void OnBODYChanged();
    partial void OnTEMPLATE_IDChanging(System.Nullable<int> value);
    partial void OnTEMPLATE_IDChanged();
    partial void OnSTATUS_IDChanging(byte value);
    partial void OnSTATUS_IDChanged();
    partial void OnSUBMITTEDChanging(System.Nullable<System.DateTime> value);
    partial void OnSUBMITTEDChanged();
    partial void OnHTML_TEMPLATE_IDChanging(System.Nullable<long> value);
    partial void OnHTML_TEMPLATE_IDChanged();
    partial void OnRECIPIENT_FILTER_IDChanging(System.Nullable<long> value);
    partial void OnRECIPIENT_FILTER_IDChanged();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnCREATEDChanging(System.DateTime value);
    partial void OnCREATEDChanged();
    partial void OnUPDATE_USER_IDChanging(System.Nullable<System.Guid> value);
    partial void OnUPDATE_USER_IDChanged();
    partial void OnDELETE_USER_IDChanging(System.Nullable<System.Guid> value);
    partial void OnDELETE_USER_IDChanged();
    partial void OnDATE_CREATEDChanging(System.DateTime value);
    partial void OnDATE_CREATEDChanged();
    partial void OnDATE_UPDATEDChanging(System.Nullable<System.DateTime> value);
    partial void OnDATE_UPDATEDChanged();
    partial void OnDATE_DELETEDChanging(System.Nullable<System.DateTime> value);
    partial void OnDATE_DELETEDChanged();
    partial void OnVERSIONChanging(System.Data.Linq.Binary value);
    partial void OnVERSIONChanged();
    partial void OnENTITYChanging(string value);
    partial void OnENTITYChanged();
    partial void OnENTITY_IDChanging(string value);
    partial void OnENTITY_IDChanged();
    partial void OnMSGTYPEChanging(System.Nullable<int> value);
    partial void OnMSGTYPEChanged();
    partial void OnisLinkChanging(System.Nullable<bool> value);
    partial void OnisLinkChanged();
    partial void OnFB_URLChanging(string value);
    partial void OnFB_URLChanged();
    partial void OnREPLACE_EMAILChanging(System.Nullable<bool> value);
    partial void OnREPLACE_EMAILChanged();
    partial void OnFB_PhotoUrlChanging(string value);
    partial void OnFB_PhotoUrlChanged();
    partial void OnFB_SourceUrlChanging(string value);
    partial void OnFB_SourceUrlChanged();
    partial void OnisSenderIDChanging(System.Nullable<bool> value);
    partial void OnisSenderIDChanged();
    partial void OnTO_ADDRESSChanging(string value);
    partial void OnTO_ADDRESSChanged();
    partial void OnTO_NAMEChanging(string value);
    partial void OnTO_NAMEChanged();
    #endregion
		
		public COM_MESSAGE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESSAGE_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int MESSAGE_ID
		{
			get
			{
				return this._MESSAGE_ID;
			}
			set
			{
				if ((this._MESSAGE_ID != value))
				{
					this.OnMESSAGE_IDChanging(value);
					this.SendPropertyChanging();
					this._MESSAGE_ID = value;
					this.SendPropertyChanged("MESSAGE_ID");
					this.OnMESSAGE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="NVarChar(500) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this.OnDESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPTION = value;
					this.SendPropertyChanged("DESCRIPTION");
					this.OnDESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBJECT", DbType="NVarChar(300)", UpdateCheck=UpdateCheck.Never)]
		public string SUBJECT
		{
			get
			{
				return this._SUBJECT;
			}
			set
			{
				if ((this._SUBJECT != value))
				{
					this.OnSUBJECTChanging(value);
					this.SendPropertyChanging();
					this._SUBJECT = value;
					this.SendPropertyChanged("SUBJECT");
					this.OnSUBJECTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FROM_ADDRESS", DbType="NVarChar(256) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string FROM_ADDRESS
		{
			get
			{
				return this._FROM_ADDRESS;
			}
			set
			{
				if ((this._FROM_ADDRESS != value))
				{
					this.OnFROM_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._FROM_ADDRESS = value;
					this.SendPropertyChanged("FROM_ADDRESS");
					this.OnFROM_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FROM_NAME", DbType="NVarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string FROM_NAME
		{
			get
			{
				return this._FROM_NAME;
			}
			set
			{
				if ((this._FROM_NAME != value))
				{
					this.OnFROM_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FROM_NAME = value;
					this.SendPropertyChanged("FROM_NAME");
					this.OnFROM_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC", DbType="NVarChar(256)", UpdateCheck=UpdateCheck.Never)]
		public string CC
		{
			get
			{
				return this._CC;
			}
			set
			{
				if ((this._CC != value))
				{
					this.OnCCChanging(value);
					this.SendPropertyChanging();
					this._CC = value;
					this.SendPropertyChanged("CC");
					this.OnCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCC", DbType="NVarChar(256)", UpdateCheck=UpdateCheck.Never)]
		public string BCC
		{
			get
			{
				return this._BCC;
			}
			set
			{
				if ((this._BCC != value))
				{
					this.OnBCCChanging(value);
					this.SendPropertyChanging();
					this._BCC = value;
					this.SendPropertyChanged("BCC");
					this.OnBCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL_ID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int CHANNEL_ID
		{
			get
			{
				return this._CHANNEL_ID;
			}
			set
			{
				if ((this._CHANNEL_ID != value))
				{
					this.OnCHANNEL_IDChanging(value);
					this.SendPropertyChanging();
					this._CHANNEL_ID = value;
					this.SendPropertyChanged("CHANNEL_ID");
					this.OnCHANNEL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FORMAT_ID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int FORMAT_ID
		{
			get
			{
				return this._FORMAT_ID;
			}
			set
			{
				if ((this._FORMAT_ID != value))
				{
					this.OnFORMAT_IDChanging(value);
					this.SendPropertyChanging();
					this._FORMAT_ID = value;
					this.SendPropertyChanged("FORMAT_ID");
					this.OnFORMAT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BODY", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string BODY
		{
			get
			{
				return this._BODY;
			}
			set
			{
				if ((this._BODY != value))
				{
					this.OnBODYChanging(value);
					this.SendPropertyChanging();
					this._BODY = value;
					this.SendPropertyChanged("BODY");
					this.OnBODYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEMPLATE_ID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> TEMPLATE_ID
		{
			get
			{
				return this._TEMPLATE_ID;
			}
			set
			{
				if ((this._TEMPLATE_ID != value))
				{
					this.OnTEMPLATE_IDChanging(value);
					this.SendPropertyChanging();
					this._TEMPLATE_ID = value;
					this.SendPropertyChanged("TEMPLATE_ID");
					this.OnTEMPLATE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_ID", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte STATUS_ID
		{
			get
			{
				return this._STATUS_ID;
			}
			set
			{
				if ((this._STATUS_ID != value))
				{
					this.OnSTATUS_IDChanging(value);
					this.SendPropertyChanging();
					this._STATUS_ID = value;
					this.SendPropertyChanged("STATUS_ID");
					this.OnSTATUS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBMITTED", DbType="SmallDateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> SUBMITTED
		{
			get
			{
				return this._SUBMITTED;
			}
			set
			{
				if ((this._SUBMITTED != value))
				{
					this.OnSUBMITTEDChanging(value);
					this.SendPropertyChanging();
					this._SUBMITTED = value;
					this.SendPropertyChanged("SUBMITTED");
					this.OnSUBMITTEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HTML_TEMPLATE_ID", DbType="BigInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<long> HTML_TEMPLATE_ID
		{
			get
			{
				return this._HTML_TEMPLATE_ID;
			}
			set
			{
				if ((this._HTML_TEMPLATE_ID != value))
				{
					this.OnHTML_TEMPLATE_IDChanging(value);
					this.SendPropertyChanging();
					this._HTML_TEMPLATE_ID = value;
					this.SendPropertyChanged("HTML_TEMPLATE_ID");
					this.OnHTML_TEMPLATE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECIPIENT_FILTER_ID", DbType="BigInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<long> RECIPIENT_FILTER_ID
		{
			get
			{
				return this._RECIPIENT_FILTER_ID;
			}
			set
			{
				if ((this._RECIPIENT_FILTER_ID != value))
				{
					this.OnRECIPIENT_FILTER_IDChanging(value);
					this.SendPropertyChanging();
					this._RECIPIENT_FILTER_ID = value;
					this.SendPropertyChanged("RECIPIENT_FILTER_ID");
					this.OnRECIPIENT_FILTER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED", DbType="SmallDateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime CREATED
		{
			get
			{
				return this._CREATED;
			}
			set
			{
				if ((this._CREATED != value))
				{
					this.OnCREATEDChanging(value);
					this.SendPropertyChanging();
					this._CREATED = value;
					this.SendPropertyChanged("CREATED");
					this.OnCREATEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATE_USER_ID", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> UPDATE_USER_ID
		{
			get
			{
				return this._UPDATE_USER_ID;
			}
			set
			{
				if ((this._UPDATE_USER_ID != value))
				{
					this.OnUPDATE_USER_IDChanging(value);
					this.SendPropertyChanging();
					this._UPDATE_USER_ID = value;
					this.SendPropertyChanged("UPDATE_USER_ID");
					this.OnUPDATE_USER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELETE_USER_ID", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> DELETE_USER_ID
		{
			get
			{
				return this._DELETE_USER_ID;
			}
			set
			{
				if ((this._DELETE_USER_ID != value))
				{
					this.OnDELETE_USER_IDChanging(value);
					this.SendPropertyChanging();
					this._DELETE_USER_ID = value;
					this.SendPropertyChanged("DELETE_USER_ID");
					this.OnDELETE_USER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_CREATED", DbType="SmallDateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime DATE_CREATED
		{
			get
			{
				return this._DATE_CREATED;
			}
			set
			{
				if ((this._DATE_CREATED != value))
				{
					this.OnDATE_CREATEDChanging(value);
					this.SendPropertyChanging();
					this._DATE_CREATED = value;
					this.SendPropertyChanged("DATE_CREATED");
					this.OnDATE_CREATEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_UPDATED", DbType="SmallDateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DATE_UPDATED
		{
			get
			{
				return this._DATE_UPDATED;
			}
			set
			{
				if ((this._DATE_UPDATED != value))
				{
					this.OnDATE_UPDATEDChanging(value);
					this.SendPropertyChanging();
					this._DATE_UPDATED = value;
					this.SendPropertyChanged("DATE_UPDATED");
					this.OnDATE_UPDATEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_DELETED", DbType="SmallDateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DATE_DELETED
		{
			get
			{
				return this._DATE_DELETED;
			}
			set
			{
				if ((this._DATE_DELETED != value))
				{
					this.OnDATE_DELETEDChanging(value);
					this.SendPropertyChanging();
					this._DATE_DELETED = value;
					this.SendPropertyChanged("DATE_DELETED");
					this.OnDATE_DELETEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERSION", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary VERSION
		{
			get
			{
				return this._VERSION;
			}
			set
			{
				if ((this._VERSION != value))
				{
					this.OnVERSIONChanging(value);
					this.SendPropertyChanging();
					this._VERSION = value;
					this.SendPropertyChanged("VERSION");
					this.OnVERSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTITY", DbType="Char(16)", UpdateCheck=UpdateCheck.Never)]
		public string ENTITY
		{
			get
			{
				return this._ENTITY;
			}
			set
			{
				if ((this._ENTITY != value))
				{
					this.OnENTITYChanging(value);
					this.SendPropertyChanging();
					this._ENTITY = value;
					this.SendPropertyChanged("ENTITY");
					this.OnENTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTITY_ID", DbType="VarChar(32)", UpdateCheck=UpdateCheck.Never)]
		public string ENTITY_ID
		{
			get
			{
				return this._ENTITY_ID;
			}
			set
			{
				if ((this._ENTITY_ID != value))
				{
					this.OnENTITY_IDChanging(value);
					this.SendPropertyChanging();
					this._ENTITY_ID = value;
					this.SendPropertyChanged("ENTITY_ID");
					this.OnENTITY_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSGTYPE", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> MSGTYPE
		{
			get
			{
				return this._MSGTYPE;
			}
			set
			{
				if ((this._MSGTYPE != value))
				{
					this.OnMSGTYPEChanging(value);
					this.SendPropertyChanging();
					this._MSGTYPE = value;
					this.SendPropertyChanged("MSGTYPE");
					this.OnMSGTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isLink", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> isLink
		{
			get
			{
				return this._isLink;
			}
			set
			{
				if ((this._isLink != value))
				{
					this.OnisLinkChanging(value);
					this.SendPropertyChanging();
					this._isLink = value;
					this.SendPropertyChanged("isLink");
					this.OnisLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FB_URL", DbType="VarChar(256)", UpdateCheck=UpdateCheck.Never)]
		public string FB_URL
		{
			get
			{
				return this._FB_URL;
			}
			set
			{
				if ((this._FB_URL != value))
				{
					this.OnFB_URLChanging(value);
					this.SendPropertyChanging();
					this._FB_URL = value;
					this.SendPropertyChanged("FB_URL");
					this.OnFB_URLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPLACE_EMAIL", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> REPLACE_EMAIL
		{
			get
			{
				return this._REPLACE_EMAIL;
			}
			set
			{
				if ((this._REPLACE_EMAIL != value))
				{
					this.OnREPLACE_EMAILChanging(value);
					this.SendPropertyChanging();
					this._REPLACE_EMAIL = value;
					this.SendPropertyChanged("REPLACE_EMAIL");
					this.OnREPLACE_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FB_PhotoUrl", DbType="NVarChar(256)", UpdateCheck=UpdateCheck.Never)]
		public string FB_PhotoUrl
		{
			get
			{
				return this._FB_PhotoUrl;
			}
			set
			{
				if ((this._FB_PhotoUrl != value))
				{
					this.OnFB_PhotoUrlChanging(value);
					this.SendPropertyChanging();
					this._FB_PhotoUrl = value;
					this.SendPropertyChanged("FB_PhotoUrl");
					this.OnFB_PhotoUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FB_SourceUrl", DbType="NVarChar(256)", UpdateCheck=UpdateCheck.Never)]
		public string FB_SourceUrl
		{
			get
			{
				return this._FB_SourceUrl;
			}
			set
			{
				if ((this._FB_SourceUrl != value))
				{
					this.OnFB_SourceUrlChanging(value);
					this.SendPropertyChanging();
					this._FB_SourceUrl = value;
					this.SendPropertyChanged("FB_SourceUrl");
					this.OnFB_SourceUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isSenderID", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> isSenderID
		{
			get
			{
				return this._isSenderID;
			}
			set
			{
				if ((this._isSenderID != value))
				{
					this.OnisSenderIDChanging(value);
					this.SendPropertyChanging();
					this._isSenderID = value;
					this.SendPropertyChanged("isSenderID");
					this.OnisSenderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TO_ADDRESS", DbType="NVarChar(256)", UpdateCheck=UpdateCheck.Never)]
		public string TO_ADDRESS
		{
			get
			{
				return this._TO_ADDRESS;
			}
			set
			{
				if ((this._TO_ADDRESS != value))
				{
					this.OnTO_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._TO_ADDRESS = value;
					this.SendPropertyChanged("TO_ADDRESS");
					this.OnTO_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TO_NAME", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string TO_NAME
		{
			get
			{
				return this._TO_NAME;
			}
			set
			{
				if ((this._TO_NAME != value))
				{
					this.OnTO_NAMEChanging(value);
					this.SendPropertyChanging();
					this._TO_NAME = value;
					this.SendPropertyChanged("TO_NAME");
					this.OnTO_NAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
