#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeadServices
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MarketingAutomationTool")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertContactJob_Exception(ContactJob_Exception instance);
    partial void UpdateContactJob_Exception(ContactJob_Exception instance);
    partial void DeleteContactJob_Exception(ContactJob_Exception instance);
    partial void InsertContactJob(ContactJob instance);
    partial void UpdateContactJob(ContactJob instance);
    partial void DeleteContactJob(ContactJob instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::LeadServices.Properties.Settings.Default.MarketingAutomationToolConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<ContactJob_Exception> ContactJob_Exceptions
		{
			get
			{
				return this.GetTable<ContactJob_Exception>();
			}
		}
		
		public System.Data.Linq.Table<ContactJob> ContactJobs
		{
			get
			{
				return this.GetTable<ContactJob>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.isUniqueEmail", IsComposable=true)]
		public string isUniqueEmail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Account_Id", DbType="UniqueIdentifier")] System.Nullable<System.Guid> account_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string strEmail)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account_Id, strEmail).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S_CON_GET_TEMP_CONTACT")]
		public ISingleResult<S_CON_GET_TEMP_CONTACTResult> S_CON_GET_TEMP_CONTACT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> job_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), job_id);
			return ((ISingleResult<S_CON_GET_TEMP_CONTACTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_Country_GetCountryId", IsComposable=true)]
		public System.Nullable<int> fn_Country_GetCountryId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CountryName", DbType="NVarChar(50)")] string countryName)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), countryName).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S_CON_ADD_RECORDS_PARSER_XLS_MIN")]
		public int S_CON_ADD_RECORDS_PARSER_XLS_MIN([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> job_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), job_id, id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S_CON_CONTACT_PARSED_RECORD_TO_TMP_XLS")]
		public int SaveRecordToTempXLS(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="JOB_ID", DbType="Int")] System.Nullable<int> jOB_ID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACCOUNT_ID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> aCCOUNT_ID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FIRST_NAME", DbType="NVarChar(100)")] string fIRST_NAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LAST_NAME", DbType="NVarChar(100)")] string lAST_NAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMAIL", DbType="NVarChar(250)")] string eMAIL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MOBILE", DbType="VarChar(100)")] string mOBILE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TITLE", DbType="NVarChar(50)")] string tITLE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUBSCRIBEDTOEMAIL", DbType="Bit")] System.Nullable<bool> sUBSCRIBEDTOEMAIL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTACTTYPE", DbType="Int")] System.Nullable<int> cONTACTTYPE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTACTSTATUS", DbType="Int")] System.Nullable<int> cONTACTSTATUS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LEADSTATUS", DbType="Int")] System.Nullable<int> lEADSTATUS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GENDER", DbType="Char(1)")] System.Nullable<char> gENDER, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="COMPANY_NAME", DbType="NVarChar(100)")] string cOMPANY_NAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="WEBSITE", DbType="NVarChar(250)")] string wEBSITE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="POSITION_TITLE", DbType="NVarChar(50)")] string pOSITION_TITLE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PHONE_NO", DbType="VarChar(100)")] string pHONE_NO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ADDRESS1", DbType="NVarChar(100)")] string aDDRESS1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ADDRESS2", DbType="NVarChar(100)")] string aDDRESS2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CITY", DbType="NVarChar(50)")] string cITY, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STATE", DbType="NVarChar(50)")] string sTATE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="COUNTRYID", DbType="Int")] System.Nullable<int> cOUNTRYID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="POSTALCODE", DbType="NVarChar(20)")] string pOSTALCODE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUBSCRIBEDTOEMAILVIA", DbType="VarChar(50)")] string sUBSCRIBEDTOEMAILVIA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CREATEDBY", DbType="UniqueIdentifier")] System.Nullable<System.Guid> cREATEDBY, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUBSCRIBEDTOIPADDRESS", DbType="VarChar(15)")] string sUBSCRIBEDTOIPADDRESS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FORMID", DbType="Int")] System.Nullable<int> fORMID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTACTLISTID", DbType="Int")] System.Nullable<int> cONTACTLISTID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FILTERID", DbType="Int")] System.Nullable<int> fILTERID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), jOB_ID, aCCOUNT_ID, fIRST_NAME, lAST_NAME, eMAIL, mOBILE, tITLE, sUBSCRIBEDTOEMAIL, cONTACTTYPE, cONTACTSTATUS, lEADSTATUS, gENDER, cOMPANY_NAME, wEBSITE, pOSITION_TITLE, pHONE_NO, aDDRESS1, aDDRESS2, cITY, sTATE, cOUNTRYID, pOSTALCODE, sUBSCRIBEDTOEMAILVIA, cREATEDBY, sUBSCRIBEDTOIPADDRESS, fORMID, cONTACTLISTID, fILTERID);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _UserID;
		
		private System.Nullable<System.Guid> _AccountID;
		
		private string _UserName;
		
		private string _Password;
		
		private string _FirstName;
		
		private string _MiddleName;
		
		private string _LastName;
		
		private string _MobileNumber;
		
		private string _PhoneNumber;
		
		private string _EmailAddress;
		
		private System.Nullable<int> _CountryId;
		
		private System.Nullable<int> _PasswordQuestion;
		
		private string _PasswordAnswer;
		
		private System.Nullable<System.DateTime> _LastLoginDate;
		
		private System.Nullable<System.DateTime> _LastLogoutDate;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<System.Guid> _CreatedBy;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
		private System.Nullable<System.Guid> _ModifiedBy;
		
		private System.Nullable<bool> _IsAdmin;
		
		private System.Nullable<bool> _IsActive;
		
		private string _PasswordSalt;
		
		private int _ID;
		
		private string _Address;
		
		private string _City;
		
		private string _State;
		
		private string _ZipCode;
		
		private System.Nullable<bool> _HasChangedSystemPassword;
		
		private System.Nullable<bool> _IsOwner;
		
		private string _Position;
		
		private bool _IsSuperAdminUser;
		
		private EntitySet<ContactJob> _ContactJobs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(System.Guid value);
    partial void OnUserIDChanged();
    partial void OnAccountIDChanging(System.Nullable<System.Guid> value);
    partial void OnAccountIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnMobileNumberChanging(string value);
    partial void OnMobileNumberChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnEmailAddressChanging(string value);
    partial void OnEmailAddressChanged();
    partial void OnCountryIdChanging(System.Nullable<int> value);
    partial void OnCountryIdChanged();
    partial void OnPasswordQuestionChanging(System.Nullable<int> value);
    partial void OnPasswordQuestionChanged();
    partial void OnPasswordAnswerChanging(string value);
    partial void OnPasswordAnswerChanged();
    partial void OnLastLoginDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLoginDateChanged();
    partial void OnLastLogoutDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLogoutDateChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnCreatedByChanging(System.Nullable<System.Guid> value);
    partial void OnCreatedByChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    partial void OnModifiedByChanging(System.Nullable<System.Guid> value);
    partial void OnModifiedByChanged();
    partial void OnIsAdminChanging(System.Nullable<bool> value);
    partial void OnIsAdminChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    partial void OnPasswordSaltChanging(string value);
    partial void OnPasswordSaltChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipCodeChanging(string value);
    partial void OnZipCodeChanged();
    partial void OnHasChangedSystemPasswordChanging(System.Nullable<bool> value);
    partial void OnHasChangedSystemPasswordChanged();
    partial void OnIsOwnerChanging(System.Nullable<bool> value);
    partial void OnIsOwnerChanged();
    partial void OnPositionChanging(string value);
    partial void OnPositionChanged();
    partial void OnIsSuperAdminUserChanging(bool value);
    partial void OnIsSuperAdminUserChanged();
    #endregion
		
		public User()
		{
			this._ContactJobs = new EntitySet<ContactJob>(new Action<ContactJob>(this.attach_ContactJobs), new Action<ContactJob>(this.detach_ContactJobs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(128)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(100)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(100)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(100)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNumber", DbType="VarChar(100)")]
		public string MobileNumber
		{
			get
			{
				return this._MobileNumber;
			}
			set
			{
				if ((this._MobileNumber != value))
				{
					this.OnMobileNumberChanging(value);
					this.SendPropertyChanging();
					this._MobileNumber = value;
					this.SendPropertyChanged("MobileNumber");
					this.OnMobileNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="VarChar(100)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(250)")]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this.OnEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._EmailAddress = value;
					this.SendPropertyChanged("EmailAddress");
					this.OnEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryId", DbType="Int")]
		public System.Nullable<int> CountryId
		{
			get
			{
				return this._CountryId;
			}
			set
			{
				if ((this._CountryId != value))
				{
					this.OnCountryIdChanging(value);
					this.SendPropertyChanging();
					this._CountryId = value;
					this.SendPropertyChanged("CountryId");
					this.OnCountryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordQuestion", DbType="Int")]
		public System.Nullable<int> PasswordQuestion
		{
			get
			{
				return this._PasswordQuestion;
			}
			set
			{
				if ((this._PasswordQuestion != value))
				{
					this.OnPasswordQuestionChanging(value);
					this.SendPropertyChanging();
					this._PasswordQuestion = value;
					this.SendPropertyChanged("PasswordQuestion");
					this.OnPasswordQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordAnswer", DbType="NVarChar(1000)")]
		public string PasswordAnswer
		{
			get
			{
				return this._PasswordAnswer;
			}
			set
			{
				if ((this._PasswordAnswer != value))
				{
					this.OnPasswordAnswerChanging(value);
					this.SendPropertyChanging();
					this._PasswordAnswer = value;
					this.SendPropertyChanged("PasswordAnswer");
					this.OnPasswordAnswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastLoginDate
		{
			get
			{
				return this._LastLoginDate;
			}
			set
			{
				if ((this._LastLoginDate != value))
				{
					this.OnLastLoginDateChanging(value);
					this.SendPropertyChanging();
					this._LastLoginDate = value;
					this.SendPropertyChanged("LastLoginDate");
					this.OnLastLoginDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLogoutDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastLogoutDate
		{
			get
			{
				return this._LastLogoutDate;
			}
			set
			{
				if ((this._LastLogoutDate != value))
				{
					this.OnLastLogoutDateChanging(value);
					this.SendPropertyChanging();
					this._LastLogoutDate = value;
					this.SendPropertyChanged("LastLogoutDate");
					this.OnLastLogoutDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this.OnModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDate = value;
					this.SendPropertyChanged("ModifiedDate");
					this.OnModifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this.OnModifiedByChanging(value);
					this.SendPropertyChanging();
					this._ModifiedBy = value;
					this.SendPropertyChanged("ModifiedBy");
					this.OnModifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdmin", DbType="Bit")]
		public System.Nullable<bool> IsAdmin
		{
			get
			{
				return this._IsAdmin;
			}
			set
			{
				if ((this._IsAdmin != value))
				{
					this.OnIsAdminChanging(value);
					this.SendPropertyChanging();
					this._IsAdmin = value;
					this.SendPropertyChanged("IsAdmin");
					this.OnIsAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordSalt", DbType="NVarChar(128)")]
		public string PasswordSalt
		{
			get
			{
				return this._PasswordSalt;
			}
			set
			{
				if ((this._PasswordSalt != value))
				{
					this.OnPasswordSaltChanging(value);
					this.SendPropertyChanging();
					this._PasswordSalt = value;
					this.SendPropertyChanged("PasswordSalt");
					this.OnPasswordSaltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(250)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(100)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(100)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode", DbType="NVarChar(20)")]
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				if ((this._ZipCode != value))
				{
					this.OnZipCodeChanging(value);
					this.SendPropertyChanging();
					this._ZipCode = value;
					this.SendPropertyChanged("ZipCode");
					this.OnZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasChangedSystemPassword", DbType="Bit")]
		public System.Nullable<bool> HasChangedSystemPassword
		{
			get
			{
				return this._HasChangedSystemPassword;
			}
			set
			{
				if ((this._HasChangedSystemPassword != value))
				{
					this.OnHasChangedSystemPasswordChanging(value);
					this.SendPropertyChanging();
					this._HasChangedSystemPassword = value;
					this.SendPropertyChanged("HasChangedSystemPassword");
					this.OnHasChangedSystemPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsOwner", DbType="Bit")]
		public System.Nullable<bool> IsOwner
		{
			get
			{
				return this._IsOwner;
			}
			set
			{
				if ((this._IsOwner != value))
				{
					this.OnIsOwnerChanging(value);
					this.SendPropertyChanging();
					this._IsOwner = value;
					this.SendPropertyChanged("IsOwner");
					this.OnIsOwnerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(128)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this.OnPositionChanging(value);
					this.SendPropertyChanging();
					this._Position = value;
					this.SendPropertyChanged("Position");
					this.OnPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSuperAdminUser", DbType="Bit NOT NULL")]
		public bool IsSuperAdminUser
		{
			get
			{
				return this._IsSuperAdminUser;
			}
			set
			{
				if ((this._IsSuperAdminUser != value))
				{
					this.OnIsSuperAdminUserChanging(value);
					this.SendPropertyChanging();
					this._IsSuperAdminUser = value;
					this.SendPropertyChanged("IsSuperAdminUser");
					this.OnIsSuperAdminUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_ContactJob", Storage="_ContactJobs", ThisKey="UserID", OtherKey="CreatedBy")]
		public EntitySet<ContactJob> ContactJobs
		{
			get
			{
				return this._ContactJobs;
			}
			set
			{
				this._ContactJobs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ContactJobs(ContactJob entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_ContactJobs(ContactJob entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ContactJob_Exception")]
	public partial class ContactJob_Exception : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _JE_ID;
		
		private int _JOB_ID;
		
		private System.Nullable<int> _REC_NO;
		
		private string _ERR_CODE;
		
		private string _DESCRIPTION;
		
		private System.DateTime _DATE_CREATED;
		
		private EntityRef<ContactJob> _ContactJob;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJE_IDChanging(int value);
    partial void OnJE_IDChanged();
    partial void OnJOB_IDChanging(int value);
    partial void OnJOB_IDChanged();
    partial void OnREC_NOChanging(System.Nullable<int> value);
    partial void OnREC_NOChanged();
    partial void OnERR_CODEChanging(string value);
    partial void OnERR_CODEChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    partial void OnDATE_CREATEDChanging(System.DateTime value);
    partial void OnDATE_CREATEDChanged();
    #endregion
		
		public ContactJob_Exception()
		{
			this._ContactJob = default(EntityRef<ContactJob>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JE_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int JE_ID
		{
			get
			{
				return this._JE_ID;
			}
			set
			{
				if ((this._JE_ID != value))
				{
					this.OnJE_IDChanging(value);
					this.SendPropertyChanging();
					this._JE_ID = value;
					this.SendPropertyChanged("JE_ID");
					this.OnJE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_ID", DbType="Int NOT NULL")]
		public int JOB_ID
		{
			get
			{
				return this._JOB_ID;
			}
			set
			{
				if ((this._JOB_ID != value))
				{
					if (this._ContactJob.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnJOB_IDChanging(value);
					this.SendPropertyChanging();
					this._JOB_ID = value;
					this.SendPropertyChanged("JOB_ID");
					this.OnJOB_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REC_NO", DbType="Int")]
		public System.Nullable<int> REC_NO
		{
			get
			{
				return this._REC_NO;
			}
			set
			{
				if ((this._REC_NO != value))
				{
					this.OnREC_NOChanging(value);
					this.SendPropertyChanging();
					this._REC_NO = value;
					this.SendPropertyChanged("REC_NO");
					this.OnREC_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ERR_CODE", DbType="VarChar(50)")]
		public string ERR_CODE
		{
			get
			{
				return this._ERR_CODE;
			}
			set
			{
				if ((this._ERR_CODE != value))
				{
					this.OnERR_CODEChanging(value);
					this.SendPropertyChanging();
					this._ERR_CODE = value;
					this.SendPropertyChanged("ERR_CODE");
					this.OnERR_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="NVarChar(MAX)")]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this.OnDESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPTION = value;
					this.SendPropertyChanged("DESCRIPTION");
					this.OnDESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_CREATED", DbType="SmallDateTime NOT NULL", IsDbGenerated=true)]
		public System.DateTime DATE_CREATED
		{
			get
			{
				return this._DATE_CREATED;
			}
			set
			{
				if ((this._DATE_CREATED != value))
				{
					this.OnDATE_CREATEDChanging(value);
					this.SendPropertyChanging();
					this._DATE_CREATED = value;
					this.SendPropertyChanged("DATE_CREATED");
					this.OnDATE_CREATEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ContactJob_ContactJob_Exception", Storage="_ContactJob", ThisKey="JOB_ID", OtherKey="JobId", IsForeignKey=true)]
		public ContactJob ContactJob
		{
			get
			{
				return this._ContactJob.Entity;
			}
			set
			{
				ContactJob previousValue = this._ContactJob.Entity;
				if (((previousValue != value) 
							|| (this._ContactJob.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ContactJob.Entity = null;
						previousValue.ContactJob_Exceptions.Remove(this);
					}
					this._ContactJob.Entity = value;
					if ((value != null))
					{
						value.ContactJob_Exceptions.Add(this);
						this._JOB_ID = value.JobId;
					}
					else
					{
						this._JOB_ID = default(int);
					}
					this.SendPropertyChanged("ContactJob");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ContactJob")]
	public partial class ContactJob : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _JobId;
		
		private string _JobName;
		
		private byte _JobStatusId;
		
		private System.Guid _AccountID;
		
		private System.Guid _CreatedBy;
		
		private string _FileFormat;
		
		private string _OriginalFileName;
		
		private string _FileName;
		
		private System.Nullable<int> _ContactListId;
		
		private System.DateTime _DateCreated;
		
		private System.Nullable<System.DateTime> _JobStarted;
		
		private System.Nullable<System.DateTime> _JobFinished;
		
		private string _Error;
		
		private System.Nullable<int> _TotalContacts;
		
		private System.Nullable<int> _UploadedContacts;
		
		private System.Nullable<int> _CurrentRowParsedInExcel;
		
		private string _IPAddress;
		
		private EntitySet<ContactJob_Exception> _ContactJob_Exceptions;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJobIdChanging(int value);
    partial void OnJobIdChanged();
    partial void OnJobNameChanging(string value);
    partial void OnJobNameChanged();
    partial void OnJobStatusIdChanging(byte value);
    partial void OnJobStatusIdChanged();
    partial void OnAccountIDChanging(System.Guid value);
    partial void OnAccountIDChanged();
    partial void OnCreatedByChanging(System.Guid value);
    partial void OnCreatedByChanged();
    partial void OnFileFormatChanging(string value);
    partial void OnFileFormatChanged();
    partial void OnOriginalFileNameChanging(string value);
    partial void OnOriginalFileNameChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnContactListIdChanging(System.Nullable<int> value);
    partial void OnContactListIdChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnJobStartedChanging(System.Nullable<System.DateTime> value);
    partial void OnJobStartedChanged();
    partial void OnJobFinishedChanging(System.Nullable<System.DateTime> value);
    partial void OnJobFinishedChanged();
    partial void OnErrorChanging(string value);
    partial void OnErrorChanged();
    partial void OnTotalContactsChanging(System.Nullable<int> value);
    partial void OnTotalContactsChanged();
    partial void OnUploadedContactsChanging(System.Nullable<int> value);
    partial void OnUploadedContactsChanged();
    partial void OnCurrentRowParsedInExcelChanging(System.Nullable<int> value);
    partial void OnCurrentRowParsedInExcelChanged();
    partial void OnIPAddressChanging(string value);
    partial void OnIPAddressChanged();
    #endregion
		
		public ContactJob()
		{
			this._ContactJob_Exceptions = new EntitySet<ContactJob_Exception>(new Action<ContactJob_Exception>(this.attach_ContactJob_Exceptions), new Action<ContactJob_Exception>(this.detach_ContactJob_Exceptions));
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int JobId
		{
			get
			{
				return this._JobId;
			}
			set
			{
				if ((this._JobId != value))
				{
					this.OnJobIdChanging(value);
					this.SendPropertyChanging();
					this._JobId = value;
					this.SendPropertyChanged("JobId");
					this.OnJobIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string JobName
		{
			get
			{
				return this._JobName;
			}
			set
			{
				if ((this._JobName != value))
				{
					this.OnJobNameChanging(value);
					this.SendPropertyChanging();
					this._JobName = value;
					this.SendPropertyChanged("JobName");
					this.OnJobNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobStatusId", DbType="TinyInt NOT NULL")]
		public byte JobStatusId
		{
			get
			{
				return this._JobStatusId;
			}
			set
			{
				if ((this._JobStatusId != value))
				{
					this.OnJobStatusIdChanging(value);
					this.SendPropertyChanging();
					this._JobStatusId = value;
					this.SendPropertyChanged("JobStatusId");
					this.OnJobStatusIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileFormat", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string FileFormat
		{
			get
			{
				return this._FileFormat;
			}
			set
			{
				if ((this._FileFormat != value))
				{
					this.OnFileFormatChanging(value);
					this.SendPropertyChanging();
					this._FileFormat = value;
					this.SendPropertyChanged("FileFormat");
					this.OnFileFormatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalFileName", DbType="VarChar(150)")]
		public string OriginalFileName
		{
			get
			{
				return this._OriginalFileName;
			}
			set
			{
				if ((this._OriginalFileName != value))
				{
					this.OnOriginalFileNameChanging(value);
					this.SendPropertyChanging();
					this._OriginalFileName = value;
					this.SendPropertyChanged("OriginalFileName");
					this.OnOriginalFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(150)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactListId", DbType="Int")]
		public System.Nullable<int> ContactListId
		{
			get
			{
				return this._ContactListId;
			}
			set
			{
				if ((this._ContactListId != value))
				{
					this.OnContactListIdChanging(value);
					this.SendPropertyChanging();
					this._ContactListId = value;
					this.SendPropertyChanged("ContactListId");
					this.OnContactListIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="SmallDateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobStarted", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> JobStarted
		{
			get
			{
				return this._JobStarted;
			}
			set
			{
				if ((this._JobStarted != value))
				{
					this.OnJobStartedChanging(value);
					this.SendPropertyChanging();
					this._JobStarted = value;
					this.SendPropertyChanged("JobStarted");
					this.OnJobStartedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobFinished", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> JobFinished
		{
			get
			{
				return this._JobFinished;
			}
			set
			{
				if ((this._JobFinished != value))
				{
					this.OnJobFinishedChanging(value);
					this.SendPropertyChanging();
					this._JobFinished = value;
					this.SendPropertyChanged("JobFinished");
					this.OnJobFinishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this.OnErrorChanging(value);
					this.SendPropertyChanging();
					this._Error = value;
					this.SendPropertyChanged("Error");
					this.OnErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalContacts", DbType="Int")]
		public System.Nullable<int> TotalContacts
		{
			get
			{
				return this._TotalContacts;
			}
			set
			{
				if ((this._TotalContacts != value))
				{
					this.OnTotalContactsChanging(value);
					this.SendPropertyChanging();
					this._TotalContacts = value;
					this.SendPropertyChanged("TotalContacts");
					this.OnTotalContactsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadedContacts", DbType="Int")]
		public System.Nullable<int> UploadedContacts
		{
			get
			{
				return this._UploadedContacts;
			}
			set
			{
				if ((this._UploadedContacts != value))
				{
					this.OnUploadedContactsChanging(value);
					this.SendPropertyChanging();
					this._UploadedContacts = value;
					this.SendPropertyChanged("UploadedContacts");
					this.OnUploadedContactsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentRowParsedInExcel", DbType="Int")]
		public System.Nullable<int> CurrentRowParsedInExcel
		{
			get
			{
				return this._CurrentRowParsedInExcel;
			}
			set
			{
				if ((this._CurrentRowParsedInExcel != value))
				{
					this.OnCurrentRowParsedInExcelChanging(value);
					this.SendPropertyChanging();
					this._CurrentRowParsedInExcel = value;
					this.SendPropertyChanged("CurrentRowParsedInExcel");
					this.OnCurrentRowParsedInExcelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPAddress", DbType="VarChar(15)")]
		public string IPAddress
		{
			get
			{
				return this._IPAddress;
			}
			set
			{
				if ((this._IPAddress != value))
				{
					this.OnIPAddressChanging(value);
					this.SendPropertyChanging();
					this._IPAddress = value;
					this.SendPropertyChanged("IPAddress");
					this.OnIPAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ContactJob_ContactJob_Exception", Storage="_ContactJob_Exceptions", ThisKey="JobId", OtherKey="JOB_ID")]
		public EntitySet<ContactJob_Exception> ContactJob_Exceptions
		{
			get
			{
				return this._ContactJob_Exceptions;
			}
			set
			{
				this._ContactJob_Exceptions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_ContactJob", Storage="_User", ThisKey="CreatedBy", OtherKey="UserID", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.ContactJobs.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.ContactJobs.Add(this);
						this._CreatedBy = value.UserID;
					}
					else
					{
						this._CreatedBy = default(System.Guid);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ContactJob_Exceptions(ContactJob_Exception entity)
		{
			this.SendPropertyChanging();
			entity.ContactJob = this;
		}
		
		private void detach_ContactJob_Exceptions(ContactJob_Exception entity)
		{
			this.SendPropertyChanging();
			entity.ContactJob = null;
		}
	}
	
	public partial class S_CON_GET_TEMP_CONTACTResult
	{
		
		private System.Nullable<int> _ID;
		
		public S_CON_GET_TEMP_CONTACTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
