CREATE PROCEDURE S_Lead_GetRecentDetails
@ACCOUNTID UNIQUEIDENTIFIER,
@CONTACTID UNIQUEIDENTIFIER
AS
BEGIN

DECLARE @EMAIL_ADDRESS NVARCHAR(250)
DECLARE @COUNTRY_CODE INT
DECLARE @CITY_NAME NVARCHAR(50)
DECLARE @REGION_NAME NVARCHAR(50)

SELECT EmailAddress,CountryId, City, [State]
FROM Contact WITH (NOLOCK)
WHERE AccountId=@AccountID AND ContactID=@ContactID

END