CREATE TABLE CampaignClickThroughs
(
ID INT IDENTITY(1,1) PRIMARY KEY,
AccountID UNIQUEIDENTIFIER NOT NULL REFERENCES Account(AccountId),
CampaignID UNIQUEIDENTIFIER NOT NULL, 
ContactId UNIQUEIDENTIFIER NOT NULL REFERENCES Contact(ContactId),
Link  NVARCHAR(MAX) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
CreatedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Contact(ContactId)
)


CREATE TABLE CampaignUnsubscribes
(
ID INT IDENTITY(1,1) PRIMARY KEY,
AccountID UNIQUEIDENTIFIER NOT NULL REFERENCES Account(AccountId),
CampaignID UNIQUEIDENTIFIER NOT NULL, 
ContactId UNIQUEIDENTIFIER NOT NULL REFERENCES Contact(ContactId),
CreatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
CreatedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Contact(ContactId)
)