CREATE TABLE ContactListJob(
	JobId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	JobName VARCHAR(50) NOT NULL,
	JobStatusId TINYINT NOT NULL,
	AccountID UNIQUEIDENTIFIER NOT NULL REFERENCES Account(AccountID),
	CreatedBy UNIQUEIDENTIFIER NOT NULL REFERENCES [User](UserID),
	FileFormat VARCHAR(5) NOT NULL,
	OriginalFileName VARCHAR(150) NULL,
	[FileName] VARCHAR(150) NULL,
	ContactListId INT NULL REFERENCES ContactList(ID),
	DateCreated SMALLDATETIME NOT NULL DEFAULT(GETDATE()),
	JobStarted SMALLDATETIME NULL,
	JobFinished SMALLDATETIME NULL,
	Error TEXT NULL,
	TotalContacts INT NULL,
	UploadedContacts INT NULL)
	
	
	
	

