use MarketingAutomationTool
CREATE TABLE Sys_Log(
	Log_Id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Entity_Id] VARCHAR(32) NULL,
	Entity_Type VARCHAR(64) NULL,
	Log_Source VARCHAR(128) NULL,
	Log_Type VARCHAR(64) NULL,
	Log_Code VARCHAR(64) NULL,
	Log_Data NVARCHAR(MAX) NOT NULL,
	[User_Id] UNIQUEIDENTIFIER NULL,
	Ip_Address VARCHAR(20) NULL,
	Date_Created SMALLDATETIME NOT NULL
)

