
ALTER PROCEDURE [dbo].[S_LEAD_TotalByMonthProgress]
@AccountID UNIQUEIDENTIFIER
AS
BEGIN

DECLARE @Data TABLE(ID INT,YEARNUM INT,MONTHNUM INT,[MONTH] NVARCHAR(25),[COUNT] INT)
DECLARE @Months TABLE(MONTHNUM INT)
DECLARE @MinMonth INT
DECLARE @MaxMonth INT

SELECT TOP 6 ROW_NUMBER () OVER ( ORDER BY YEAR(DATEADD(HH,8,C.CreatedDate)),MONTH(DATEADD(HH,8,C.CreatedDate)) ) ID, 
YEAR(DATEADD(HH,8,C.CreatedDate)) [YEARNUM],
MONTH(DATEADD(HH,8,C.CreatedDate)) [MONTHNUM],
FORMAT(DATEADD(HH,8,C.CreatedDate), 'MMM', 'en-US')+' '+SUBSTRING(CAST(YEAR(DATEADD(HH,8,C.CreatedDate)) AS NVARCHAR(4)),3,2) [MONTH], 
COUNT(C.ContactID) [COUNT]
FROM Contact C WITH (NOLOCK)
LEFT JOIN Country SC WITH (NOLOCK)
ON C.CountryId = SC.CountryId
WHERE AccountID=@AccountID AND (CAST(DATEADD(HH,8,C.CreatedDate) AS DATE)<=CAST(DATEADD(HH,8,GETUTCDATE()) AS DATE))
GROUP BY YEAR(DATEADD(HH,8,C.CreatedDate)), MONTH(DATEADD(HH,8,C.CreatedDate)), FORMAT(DATEADD(HH,8,C.CreatedDate), 'MMM', 'en-US')
ORDER BY YEAR(DATEADD(HH,8,C.CreatedDate)), MONTH(DATEADD(HH,8,C.CreatedDate))

END

--EXEC S_LEAD_TotalByMonthProgress '6388071F-36BB-4823-A3ED-8770ADAE0F51'