use MarketingAutomationTool

CREATE TABLE tmp_Job_Upload
(
ID BIGINT PRIMARY KEY,
JOB INT,
FIRST_NAME NVARCHAR(100),
LAST_NAME NVARCHAR(100),
EMAIL NVARCHAR(250),
MOBILE VARCHAR(100),
ACCOUNT_ID UNIQUEIDENTIFIER,
DATE_CREATED DATETIME
)
