CREATE PROCEDURE S_LEAD_DELETELEAD
@ACCOUNT_ID UNIQUEIDENTIFIER,
@CONTACT_ID UNIQUEIDENTIFIER,
@MODIFIED_BY UNIQUEIDENTIFIER
AS
BEGIN
UPDATE CONTACT
SET IsDeleted=1,
DeletedDate=GETDATE(),
ModifiedBy=@MODIFIED_BY
WHERE AccountID=@ACCOUNT_ID AND
ContactID=@CONTACT_ID 

END