CREATE TABLE ContactSearch
(
ID INT IDENTITY PRIMARY KEY,
SEARCHUID UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()),
ACCOUNTID UNIQUEIDENTIFIER NOT NULL,
CREATEDBY UNIQUEIDENTIFIER NOT NULL,
CREATEDDATE DATETIME NOT NULL DEFAULT(GETDATE()),
MODIFIEDBY UNIQUEIDENTIFIER NULL,
MODIFIEDDATE DATETIME NULL
)





