CREATE TABLE ContactSearchFields
(
ID INT IDENTITY,
SEARCHID INT NOT NULL REFERENCES ContactSearch(ID),
ACCOUNTID UNIQUEIDENTIFIER NOT NULL,
CREATEDBY UNIQUEIDENTIFIER NOT NULL,
CREATEDDATE DATETIME NOT NULL DEFAULT(GETDATE()),
SEARCHKEY NVARCHAR(250) NOT NULL,
SEARCHOPERATOR NVARCHAR(20) NOT NULL,
SEARCHVALUE NVARCHAR(MAX) NOT NULL,
SEARCHLOGICALOPERATOR NVARCHAR(5) NOT NULL
)

