CREATE PROCEDURE S_ContactSearch_GetRecentSearches
@ACCOUNTID AS UNIQUEIDENTIFIER,
@CREATEDBY AS UNIQUEIDENTIFIER
AS
BEGIN
SELECT TOP 5 *
FROM ContactSearch WITH (NOLOCK)
WHERE AccountId=@AccountID AND CreatedBy=@CreatedBy
ORDER BY ID DESC
END