#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseLibrary
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MarketingAutomationTool")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSys_Log(Sys_Log instance);
    partial void UpdateSys_Log(Sys_Log instance);
    partial void DeleteSys_Log(Sys_Log instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::EnterpriseLibrary.Properties.Settings.Default.AutoMarketerConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Sys_Log> Sys_Logs
		{
			get
			{
				return this.GetTable<Sys_Log>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sys_Log")]
	public partial class Sys_Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Log_Id;
		
		private string _Entity_Id;
		
		private string _Entity_Type;
		
		private string _Log_Source;
		
		private string _Log_Type;
		
		private string _Log_Code;
		
		private string _Log_Data;
		
		private System.Nullable<System.Guid> _User_Id;
		
		private string _Ip_Address;
		
		private System.DateTime _Date_Created;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLog_IdChanging(long value);
    partial void OnLog_IdChanged();
    partial void OnEntity_IdChanging(string value);
    partial void OnEntity_IdChanged();
    partial void OnEntity_TypeChanging(string value);
    partial void OnEntity_TypeChanged();
    partial void OnLog_SourceChanging(string value);
    partial void OnLog_SourceChanged();
    partial void OnLog_TypeChanging(string value);
    partial void OnLog_TypeChanged();
    partial void OnLog_CodeChanging(string value);
    partial void OnLog_CodeChanged();
    partial void OnLog_DataChanging(string value);
    partial void OnLog_DataChanged();
    partial void OnUser_IdChanging(System.Nullable<System.Guid> value);
    partial void OnUser_IdChanged();
    partial void OnIp_AddressChanging(string value);
    partial void OnIp_AddressChanged();
    partial void OnDate_CreatedChanging(System.DateTime value);
    partial void OnDate_CreatedChanged();
    #endregion
		
		public Sys_Log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Log_Id
		{
			get
			{
				return this._Log_Id;
			}
			set
			{
				if ((this._Log_Id != value))
				{
					this.OnLog_IdChanging(value);
					this.SendPropertyChanging();
					this._Log_Id = value;
					this.SendPropertyChanged("Log_Id");
					this.OnLog_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entity_Id", DbType="VarChar(32)")]
		public string Entity_Id
		{
			get
			{
				return this._Entity_Id;
			}
			set
			{
				if ((this._Entity_Id != value))
				{
					this.OnEntity_IdChanging(value);
					this.SendPropertyChanging();
					this._Entity_Id = value;
					this.SendPropertyChanged("Entity_Id");
					this.OnEntity_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entity_Type", DbType="VarChar(64)")]
		public string Entity_Type
		{
			get
			{
				return this._Entity_Type;
			}
			set
			{
				if ((this._Entity_Type != value))
				{
					this.OnEntity_TypeChanging(value);
					this.SendPropertyChanging();
					this._Entity_Type = value;
					this.SendPropertyChanged("Entity_Type");
					this.OnEntity_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_Source", DbType="VarChar(128)")]
		public string Log_Source
		{
			get
			{
				return this._Log_Source;
			}
			set
			{
				if ((this._Log_Source != value))
				{
					this.OnLog_SourceChanging(value);
					this.SendPropertyChanging();
					this._Log_Source = value;
					this.SendPropertyChanged("Log_Source");
					this.OnLog_SourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_Type", DbType="VarChar(64)")]
		public string Log_Type
		{
			get
			{
				return this._Log_Type;
			}
			set
			{
				if ((this._Log_Type != value))
				{
					this.OnLog_TypeChanging(value);
					this.SendPropertyChanging();
					this._Log_Type = value;
					this.SendPropertyChanged("Log_Type");
					this.OnLog_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_Code", DbType="VarChar(64)")]
		public string Log_Code
		{
			get
			{
				return this._Log_Code;
			}
			set
			{
				if ((this._Log_Code != value))
				{
					this.OnLog_CodeChanging(value);
					this.SendPropertyChanging();
					this._Log_Code = value;
					this.SendPropertyChanged("Log_Code");
					this.OnLog_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_Data", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Log_Data
		{
			get
			{
				return this._Log_Data;
			}
			set
			{
				if ((this._Log_Data != value))
				{
					this.OnLog_DataChanging(value);
					this.SendPropertyChanging();
					this._Log_Data = value;
					this.SendPropertyChanged("Log_Data");
					this.OnLog_DataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ip_Address", DbType="VarChar(20)")]
		public string Ip_Address
		{
			get
			{
				return this._Ip_Address;
			}
			set
			{
				if ((this._Ip_Address != value))
				{
					this.OnIp_AddressChanging(value);
					this.SendPropertyChanging();
					this._Ip_Address = value;
					this.SendPropertyChanged("Ip_Address");
					this.OnIp_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Created", DbType="SmallDateTime NOT NULL", IsDbGenerated=true)]
		public System.DateTime Date_Created
		{
			get
			{
				return this._Date_Created;
			}
			set
			{
				if ((this._Date_Created != value))
				{
					this.OnDate_CreatedChanging(value);
					this.SendPropertyChanging();
					this._Date_Created = value;
					this.SendPropertyChanged("Date_Created");
					this.OnDate_CreatedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
